name: "Build On Windows"

on: [push]

jobs:
  build: # job id, can be any string
    # Job name is Build And Publish
    name: Build
    # This job runs on Linux
    strategy:
      matrix:
        os: [windows-latest]
        rust: [stable]
        target:
          [x86_64-pc-windows-msvc, i686-pc-windows-msvc]
    # x86_64-pc-windows-gnu, i686-pc-windows-gnu, # Github Action has no openssl on mingw32
    runs-on: ${{ matrix.os }}
    env:
      VCPKGRS_DYNAMIC: 0
      OPENSSL_STATIC: 1
      OPENSSL_NO_VENDOR: 1
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Install OpenSSL
        shell: bash
        run: |
          if [[ "${{ matrix.target }}" == "i686-pc-windows-msvc" ]] || [[ "${{ matrix.target }}" == "i686-pc-windows-gnu" ]]; then
            vcpkg install openssl --triplet x86-windows
            vcpkg install openssl --triplet x86-windows-static
          else
            vcpkg install openssl --triplet x64-windows
            vcpkg install openssl --triplet x64-windows-static
          fi
      - name: Build
        shell: bash
        run: |
          env VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT cargo build --features with-vcpkg --release --verbose --target ${{ matrix.target }}
      - name: Run tests
        shell: bash
        run: |
          env VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT cargo test --features with-vcpkg --release --verbose --target ${{ matrix.target }}
